// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskMgtSystemWebApi.Models;

#nullable disable

namespace TaskMgtSystemWebApi.Migrations
{
    [DbContext(typeof(TaskManagementDBContext))]
    partial class TaskManagementDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskMgtSystemWebApi.Models.ProjectTb", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("ProjectTb");
                });

            modelBuilder.Entity("TaskMgtSystemWebApi.Models.RoleTb", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("RoleTb");
                });

            modelBuilder.Entity("TaskMgtSystemWebApi.Models.TaskTb", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectObjProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserObjUserId")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("ProjectObjProjectId");

                    b.HasIndex("UserObjUserId");

                    b.ToTable("TaskTb");
                });

            modelBuilder.Entity("TaskMgtSystemWebApi.Models.UserTb", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("Role_ObjRoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Role_ObjRoleId");

                    b.ToTable("UserTb");
                });

            modelBuilder.Entity("TaskMgtSystemWebApi.Models.TaskTb", b =>
                {
                    b.HasOne("TaskMgtSystemWebApi.Models.ProjectTb", "ProjectObj")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectObjProjectId");

                    b.HasOne("TaskMgtSystemWebApi.Models.UserTb", "UserObj")
                        .WithMany("Tasks")
                        .HasForeignKey("UserObjUserId");

                    b.Navigation("ProjectObj");

                    b.Navigation("UserObj");
                });

            modelBuilder.Entity("TaskMgtSystemWebApi.Models.UserTb", b =>
                {
                    b.HasOne("TaskMgtSystemWebApi.Models.RoleTb", "Role_Obj")
                        .WithMany("Users")
                        .HasForeignKey("Role_ObjRoleId");

                    b.Navigation("Role_Obj");
                });

            modelBuilder.Entity("TaskMgtSystemWebApi.Models.ProjectTb", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskMgtSystemWebApi.Models.RoleTb", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaskMgtSystemWebApi.Models.UserTb", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
